# Generated by Django 5.2 on 2025-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
