services:
    django:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        environment:
            - DEBUG=True
# https://github.com/0MAVM0/News_Web.git